# Generated by Django 4.0.3 on 2022-04-22 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_uploadcsv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadcsv',
            name='numericfile',
        ),
    ]
